---
filename_to_execute: "table.sql"
#login_username: "root"
#login_password: "rootroot"
#login_port: "1433"
#login_host: "my-db-instance.chhlks3y2gpy.ap-south-1.rds.amazonaws.com"
database_name: "testdb"
path_to_sql_script: "/home/ubuntu/"
